domain = "localhost"

[account]
email = "root@example.com"
directory = "https://127.0.0.1:14000/dir"
accept_tos = true

[authentication]
method = "http-01/standalone"
[authentication.options]
port = "5002"

[[installs]]

[installs.key]
path = "/tmp/path.key"
perm = "0600"
owner = "root"
group = "root"

[installs.crt]
path = "/tmp/path.crt"
perm = "0644"
owner = "root"
group = "root"

[installs.ca]
path = "/tmp/ca.crt"
perm = "0644"
owner = "root"
group = "root"
